# URL com o padrão jdbc: e o host do pooler
spring.datasource.url=jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

# Seu novo usuário gerado pelo Supabase
spring.datasource.username=postgres.fwgsjakgqfqnxhyvndrs

# Sua senha
spring.datasource.password=NM5ItBHPDiQB3JCk

# Dialeto do PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect